#!/bin/bash

# 														EMCS Labs
# 														Hyungwon Yang
# 														hyung8758@gmail.com

# This scritp generates 'path.sh' after collecting kaldi root information of the user.
# It also links steps, and utils paths.

if [ $# -ne 1 ]; then
   echo "kadi directory should be assigned." && exit 1
fi

kaldi=$1

if [ -f $PWD/path.sh ]; then 
	echo "" > path.sh
	echo "Previously written path.sh is removed."
fi

# KALDI_ROOT
export KALDI_ROOT=$kaldi
if [ -f $KALDI_ROOT/tools/env.sh ]; then
	. $KALDI_ROOT/tools/env.sh
else 
	echo "$KALDI_ROOT/tools/env.sh is not present." && exit 1
fi

# Connect steps and utils folders to the directory.
[ ! -d $PWD/steps ] && ln -s $KALDI_ROOT/egs/wsj/s5/steps $PWD/steps
[ ! -d $PWD/utils ] && ln -s $KALDI_ROOT/egs/wsj/s5/utils $PWD/utils
export PATH=$PATH:$PWD:$PWD/utils/:$PWD/steps:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/irstlm/bin/
if [ -f $KALDI_ROOT/tools/config/common_path.sh ]; then
	. $KALDI_ROOT/tools/config/common_path.sh
else
	echo "$KALDI_ROOT/tools/config/common_path.sh is not present" && exit 1
fi
export LC_ALL=C

# Make a path.sh.
cat > path.sh << EOL
# EMCS Labs.
# This script is generated by ./local/make_path.sh. Therefore it might be different from other path.sh script.

export KALDI_ROOT=$kaldi
[ -f $KALDI_ROOT/tools/env.sh ] && . $KALDI_ROOT/tools/env.sh
export PATH=$PWD/utils/:$KALDI_ROOT/tools/openfst/bin:$PWD:$PATH
[ ! -f $KALDI_ROOT/tools/config/common_path.sh ] && echo >&2 "The standard file $KALDI_ROOT/tools/config/common_path.sh is not present -> Exit!" && exit 1
. $KALDI_ROOT/tools/config/common_path.sh
export LC_ALL=C
EOL

echo "path.sh is newly wirtten."
